name = "site"
main = "src/worker.js"
compatibility_date = "2025-04-01"
routes = [
  { pattern = "yuron.dev", custom_domain = true },
  { pattern = "www.yuron.dev", custom_domain = true },
]

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "R2"
bucket_name = "site-assets"
